### ISSUE TITLE
[Question] Interop/shim with dbus

### ISSUE THREAD

**Issue by ngortheone** [skarnet/skabus#2]
A lot of software is built with dbus in mind. In order to avoid running 2 buses some kind of shim would help to present dbus-like interface on top of skabus. Is this possible? Is this planned? 

Thanks.

**Comment by skarnet** [comment]
Oh yes, it's definitely planned. But skabus has been on the backburner for years, and isn't going to be actively developed again for a couple more years at least, so don't expect things moving on that front any kind of soon. Sorry about that - other software takes priority 😅

**Comment by ngortheone** [comment]
Thanks!
