### ISSUE TITLE
How does skabus compare to basu?

### ISSUE THREAD

**Issue by firasuke** [skarnet/skabus#3]
Hey there,

I noticed that both `skabus` and [`basu`](https://git.sr.ht/~emersion/basu) aim to provide similar functionality.

I was wondering what the differences between the two projects were?

Thanks in advance.

**Comment by firasuke** [comment]
I happened to stumble upon the following projects as well [`dbus-broker`](https://github.com/bus1/dbus-broker) and [`ubus`](https://openwrt.org/docs/techref/ubus).

**Comment by skarnet** [comment]
As its home page is saying `basu` is the sd-bus library extracted from systemd.

skabus is a different project with a completely different codebase.

That said, I probably won't come back to working on skabus before a long time, so if you're looking for a bus, another project is probably what you want.

**Comment by firasuke** [comment]
Oh ok, that's unfortunate..

Thanks for your time!
